version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD: adminpass
      POSTGRES_USER: postgres
      POSTGRES_DB: db_library
      POSTGRES_ROOT_HOST: '%'
    ports:
      - 5432:5432
    networks:
      - library-network
  rest-with-spring-boot-library:
    image: karmiguel/library
    restart: always
    build: /
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_library?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: adminpass
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - library-network
networks:
  library-network:
    driver: bridge
