#CORS
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:4200

# Serve
server:
  port: 8090

#File
file:
  upload-dir: src/main/resources/static/img

#Security
security:
  jwt:
    token:
      secret-key: 53c37
      expire-lenght: 360000

# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_library?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: adminpass

  #Upload e Download
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

# Configuracao do Springdoc OpenAPI
springdoc:
  swagger-ui:
    use-root-path: true
  packagesToScan: io.github.karMiguel.library.controllers

