# CORS
cors:
  originPatterns:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://localhost:4200"

# Servidor
server:
  port: 8090

# Arquivos
file:
  upload-dir: src/main/resources/static/img

# Segurança
security:
  jwt:
    token:
      secret-key: 53c37
      expire-length: 360000

# Banco de Dados
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_library?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: adminpass

  # Upload e Download
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: carlosmiguel.dsa12@gmail.com
    password: ${sua_password} #htpps://myaccount.google.com/apppasswords

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

# Configuração do Springdoc OpenAPI
springdoc:
  swagger-ui:
    use-root-path: true
  packagesToScan: io.github.karMiguel.library.controllers

# API de Notícias
news:
  api:
    key: "d7bba934ec9545d98fbb26a9115172d6"
    url: "https://newsapi.org/v2/top-headlines"
